url: https://imr-framework.github.io
baseurl:

# Site settings
title: imr-framework
email: imr.framework2018@gmail.com
description: "imr-framework"


# Team names, titles and social links
people:
- name: Sairam Geethanath
  pic: 1
  position: Research Scientist
  social:
    - title: github
      url: https://github.com/sairamgeethanath

people:
- name: Pavan Poojar
  pic: 2
  position: Staff Associate
  social:
    - title: github
      url: https://github.com/PavanPoojar

- name: Enlin Qian
  pic: 3
  position: Student (PhD, Biomedical Engineering)
  social:
    - title: github
      url: https://github.com/qianenlin

- name: Gehua Tong
  pic: 4
  position: Student (PhD, Biomedical Engineering)
  social:
    - title: github
      url: https://github.com/tonggehua

- name: Keerthi Sravan Ravi
  pic: 5
  position: Student (PhD, Biomedical Engineering)
  social:
    - title: github
      url: https://github.com/sravan953

- name: Marina Jimeno Manso
  pic: 6
  position: Student (PhD, Biomedical Engineering)
  social:
    - title: github
      url: https://github.com/Mmj94

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/imr-framework

# Postal address (add as many lines as necessary)
address:
  - line: 3227 Broadway
  - line: New York, NY 10027

# Build settings
markdown: kramdown
permalink: pretty
